// All Estonian UI strings of the site live here.
export const ui = {
  nav: { search: 'Otsing', contribute: 'Panusta', about: 'Meist' },
  search: {
    label: 'Otsing',
    placeholder: 'Otsi pealkirja või kirjelduse järgi',
    results: 'sissekannet',
    noResults: 'Midagi ei leitud.',
    clear: 'Tühjenda filtrid',
  },
  facets: { type: 'Tüüp', domain: 'Valdkond', audience: 'Sihtrühm', works_with: 'Töötab koos' },
  entry: {
    trust: 'Usaldusandmed',
    maintainer: 'Haldaja',
    lastTested: 'Viimati testitud',
    verified: 'Kontrollitud',
    unverified: 'Kontrollimata',
    stale: 'Aegunud',
    staleHelp: (days: number) => `Viimasest testimisest on möödas üle ${days} päeva.`,
    license: 'Litsents',
    languages: 'Keeled',
    securityNote: 'Turvamärkus',
    install: 'Paigaldamine',
    examplePrompt: 'Näidisprompt',
    description: 'Kirjeldus',
    copy: 'Kopeeri',
    copied: 'Kopeeritud',
    source: 'Lähtekood',
    edit: 'Muuda GitHubis',
    report: 'Teata probleemist',
  },
  footer: { code: 'Kood: MIT', content: 'Sisu: CC BY 4.0' },
  contribute: { title: 'Panusta' },
  about: { title: 'Meist' },
} as const;
